config/routes.rb
Rails.application.routes.draw do
  delete 'activities/clear' => 'activities#clear', as: :activity_clear
  get 'activities' => 'activities#index', as: :activities
  get 'departments/*param' => 'departments#categories', as: :department_cat
  get 'login' => 'sessions#new', as: :log_in
  get 'logout' => 'sessions#destroy', as: :log_out
  resources :sessions, :users, :staffs, :departments, :loans, :sabbaticals, :attendances, :preferences, :reliefs, :announcements
  get 'dashboard/user' => 'dashboard#user', as: :dashboard_user
  get 'dashboard/company' => 'dashboard#company', as: :dashboard_company
  get 'dashboard/preferences' => 'dashboard#preferences', as: :dashboard_setting
  get 'dashboard/records' => 'dashboard#records', as: :dashboard_records
  get 'dashboard' => 'dashboard#index', as: :dashboard
  get 'login'   => 'sessions#new'
  get 'forgot'  => 'sessions#forgot'

  root 'sessions#new'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :staff
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/loan.rb
class Loan < ActiveRecord::Base
	belongs_to :staff
end

app/models/preference.rb
class Preference < ActiveRecord::Base
end

app/models/relief.rb
class Relief < ActiveRecord::Base
	belongs_to :staff
end

app/models/sabbatical.rb
class Sabbatical < ActiveRecord::Base
	belongs_to :staff
	validates :staff_id, presence: true
end

app/models/staff.rb
class Staff < ActiveRecord::Base
	has_many :loans, :dependent => :destroy
	has_many :sabbaticals, :dependent => :destroy
	has_many :attendances, :dependent => :destroy
	has_many :reliefs, :dependent => :destroy
	has_attached_file :avatar, bucket: 'vitabiotics-assets', styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}, default_url: ':attachment/missing.png', storage: :s3, url: ":s3_domain_url", path: "/images/:id/:style.:extension",
	s3_host_name: 's3.amazonaws.com', s3_credentials: "#{Rails.root}/config/aws.yml"
	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email
	has_attached_file :avatar, bucket: 'vitabiotics-assets', styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}, default_url: ':attachment/missing.png', storage: :s3, url: ":s3_domain_url", path: "/images/:id/:style.:extension",
	s3_host_name: 's3.amazonaws.com', s3_credentials: "#{Rails.root}/config/aws.yml"
	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
	before_filter :init
	def index
		@staffs = Staff.all
	end
	def new
		@staff = Staff.new
	end
	def create
		staff_params[:date_of_birth] = "#{params[:birth_day]} #{params[:birth_month]}, #{params[:birth_year]}"
		@staff = Staff.new(staff_params)
		if @staff.save
			Activity.new({'user_id' => current_user.id, 'activity' => "Created a new staff" }).save
			redirect_to :back, notice: 'Staff has been created'
		else
			redirect_to :back, notice: 'Failed to create staff'
		end
	end
	def show
		@staff = Staff.find(params[:id])
	end
	def edit
		@staff = Staff.find(params[:id])
	end
	def update
		@staff = Staff.find(params[:id])
		staff_params[:date_of_birth] = "#{params[:birth_day]} #{params[:birth_month]}, #{params[:birth_year]}"
		updated = @staff.update_attributes(staff_params)
		if updated
			Activity.new({'user_id' => current_user.id, 'activity' => "Updated a staff data" }).save
			redirect_to :back, notice: 'Staff updated'
		else
			render 'edit', notice: "Failed to update"
		end
	end
	def destroy
		@staff = Staff.find(params[:id])
	    if @staff.destroy
	    	Activity.new({'user_id' => current_user.id, 'activity' => "Deleted a staff" }).save
	    	redirect_to staffs_path
	    end
	end
	private
	def init
		@titles = [['Mr','mr'],['Mrs','mrs'],['Miss','miss'],['Master','master']]
		@genders = [['Male','male'],['Female','female'],['Other','others']]
		@statuses = [['Single','single'],['Married','married'],['Divorced','divorced'],['Separated','separated']]
		@preferences = Preference.find(1)
		@department = Department.all
		@designation = Department.where(parent: '')
		@departments = @department.all.map { |dept| [dept.name, dept.name.downcase] }
		@designations = @designation.all.map { |dept| [dept.name, dept.name.downcase] }
		this_year = Time.now.strftime('%Y').to_i
		oldest_year = this_year - 60 # 60 years ago. Staff should be retired if above 60
		@years = (oldest_year..this_year - 10).map { |y| [y, y] } # 10 yo as youngest staff age
		@months = Date::MONTHNAMES.map { |m| [m, m] }
		@months.delete_at(0)
		@days = (1..31).map { |d| [d, d] }
	end
	def staff_params
		params.require(:staff).permit!
	end
	def require_login
		unless session[:user_id].present?
	  		redirect_to root_url
		end
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
	def instancevars(arg)
		instance_variable_get("@#{arg}Children".gsub(' ','_'))
	end
	def nameslug(arg)
		arg.downcase[0,5]
	end
	def color_label(arg)
		"theme_#{arg.gsub(', ','_')}"
	end
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/reliefs_helper.rb
module ReliefsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/staffs/edit.html.erb
<div class="middle-block" style="width:80%"><%= content_tag :p, notice, class: 'notifier' %></div>
<section class="staffData">
	<div class="topbar">
		Edit Staff
	</div>
	<div class="entry">
		<%= form_for @staff do |f| %>
			<p class="formline">
				<%= f.label :avatar, 'Upload image' %>
				<%= f.file_field :avatar, accept: 'image/png,image/jpeg' %>
			</p>
			<p class="formline">
				<%= f.label :title %>
				<%= f.select :title, options_for_select(@titles, @staff.title) %>
			</p>
			<p class="formline"><%= f.label :surname %><%= f.text_field :surname %></p>
			<p class="formline"><%= f.label :othernames, 'Other Names' %><%= f.text_field :othernames %></p>
			<p class="formline"><%= f.label :maiden_name, 'Maiden Name' %><%= f.text_field :maiden_name %></p>
			<p class="formline">
				<%= f.label :gender %>
				<%= f.select :gender, options_for_select(@genders, @staff.gender) %>
			</p>
			<p class="formline">
				<%= label_tag :birth_year, 'Year of Birth' %>
				<%= select_tag :birth_year, options_for_select(@years, @staff.date_of_birth.to_datetime.strftime('%Y')) %>
			</p>
			<p class="formline">
				<%= label_tag :birth_month, 'Month of Birth' %>
				<%= select_tag :birth_month, options_for_select(@months, @staff.date_of_birth.to_datetime.strftime('%B')) %>
			</p>
			<p class="formline">
				<%= label_tag :birth_day, 'Day of Birth' %>
				<%= select_tag :birth_day, options_for_select(@days, @staff.date_of_birth.to_datetime.strftime('%e').gsub(' ', '')) %>
			</p>
			<p class="formline">
				<%= f.label :marital_status, 'Marital Status' %>
				<%= f.select :marital_status, options_for_select(@statuses, @staff.marital_status) %>
			</p>
			<p class="formline"><%= f.label :spouse, 'Spouse Name' %><%= f.text_field :spouse %></p>
			<p class="formline"><%= f.label :first_child, 'Name of First Child' %><%= f.text_field :first_child %></p>
			<p class="formline"><%= f.label :phone %><%= f.text_field :phone %></p>
			<p class="formline"><%= f.label :email %><%= f.email_field :email %></p>
			<p class="formline">
				<%= f.label :designation %>
				<%= f.select :designation, options_for_select(@designations, @staff.designation) %>
			</p>
			<p class="formline">
				<%= f.label :department %>
				<%= f.select :department, options_for_select(@departments, @staff.department) %>
			</p>
			<p class="formline"><%= f.label :staff_from, 'Date of Employment' %><%= f.date_field :staff_from, value: @staff.staff_from %></p>
			<p class="formline"><%= f.label :prev_employer, 'Previous Employer' %><%= f.text_field :prev_employer %></p>
			<p class="formline"><%= f.label :post_held, 'Post Held' %><%= f.text_field :post_held %></p>
			<p class="formline"><%= f.label :duty_years, 'Years of Duty' %><%= f.text_field :duty_years %></p>
			<p class="formline"><%= f.label :state %><%= f.text_field :state %></p>
			<p class="formline"><%= f.label :nationality %><%= f.text_field :nationality %></p>
			<p class="formline"><%= f.label :town, 'Local Government Area' %><%= f.text_field :town %></p>
			<p class="formline"><%= f.label :family_address, 'Family Address' %><%= f.text_field :family_address %></p>
			<p class="formline"><%= f.label :permanent_address, 'Permanet Address' %><%= f.text_field :permanent_address %></p>
			<p class="formline"><%= f.label :residence, 'Residential Address' %><%= f.text_field :residence %></p>
			<p class="formline"><%= f.label :kin, 'Next of Kin' %><%= f.text_field :kin %></p>
			<p class="formline"><%= f.label :kin_phone, "Next of Kin's Phone" %><%= f.text_field :kin_phone %></p>
			<p class="formline"><%= f.label :kin_address, "Next of Kin's Address" %><%= f.text_field :kin_address %></p>
			<p class="formline"><%= f.label :annual_salary, 'Annual Salary' %><%= f.text_field :annual_salary %></p>
			<p class="formline"><button class="btn-std">Update staff</button></p>
		<% end %>
	</div>
</section>

app/views/staffs/index.html.erb
<section class="row-two">
	<h2>Staffs</h2>
	<% @staffs.all.map do |staff| %>
	<div class="topmag10">
		<% if staff.avatar.eql? nil %>
		<%= image_tag "vader.jpg", class: 'thumbnail' %>
		<% else %>
		<img src="<%= staff.avatar %>" alt="<%= staff.surname %>" class="thumbnail">
		<% end %>
		<h3 title="<%= "#{staff.surname} #{staff.othernames}" %>">
			<%= link_to "#{staff.surname} #{staff.othernames.split(' ')[0]}", staff_path(staff.id) %>
		</h3>
		<span><%= staff.designation %></span>
	</div>
	<% end %>
</section>

app/views/staffs/new.html.erb
<div class="middle-block" style="width:80%"><%= content_tag :p, notice, class: 'notifier' %></div>
<section class="staffData">
	<div class="topbar">
		Add New Staff
	</div>
	<div class="entry">
		<%= form_for @staff do |f| %>
			<p class="formline">
				<%= f.label :avatar, 'Upload image' %>
				<%= f.file_field :avatar, accept: 'image/png,image/jpeg' %>
			</p>
			<p class="formline">
				<%= f.label :title %>
				<%= f.select :title, options_for_select(@titles) %>
			</p>
			<p class="formline"><%= f.label :surname %><%= f.text_field :surname %></p>
			<p class="formline"><%= f.label :othernames, 'Other Names' %><%= f.text_field :othernames %></p>
			<p class="formline"><%= f.label :maiden_name, 'Maiden Name' %><%= f.text_field :maiden_name %></p>
			<p class="formline">
				<%= f.label :gender %>
				<%= f.select :gender, options_for_select(@genders) %>
			</p>
			<p class="formline">
				<%= label_tag :birth_year, 'Year of Birth' %>
				<%= select_tag :birth_year, options_for_select(@years) %>
			</p>
			<p class="formline">
				<%= label_tag :birth_month, 'Month of Birth' %>
				<%= select_tag :birth_month, options_for_select(@months) %>
			</p>
			<p class="formline">
				<%= label_tag :birth_day, 'Day of Birth' %>
				<%= select_tag :birth_day, options_for_select(@days) %>
			</p>
			<p class="formline">
				<%= f.label :marital_status, 'Marital Status' %>
				<%= f.select :marital_status, options_for_select(@statuses) %>
			</p>
			<p class="formline"><%= f.label :spouse, 'Spouse Name' %><%= f.text_field :spouse %></p>
			<p class="formline"><%= f.label :first_child, 'Name of First Child' %><%= f.text_field :first_child %></p>
			<p class="formline"><%= f.label :phone %><%= f.text_field :phone %></p>
			<p class="formline"><%= f.label :email %><%= f.email_field :email %></p>
			<p class="formline">
				<%= f.label :designation %>
				<%= f.select :designation, options_for_select(@designations) %>
			</p>
			<p class="formline">
				<%= f.label :department %>
				<%= f.select :department, options_for_select(@departments) %>
			</p>
			<p class="formline"><%= f.label :staff_from, 'Date of Employment' %><%= f.date_field :staff_from %></p>
			<p class="formline"><%= f.label :prev_employer, 'Previous Employer' %><%= f.text_field :prev_employer %></p>
			<p class="formline"><%= f.label :post_held, 'Post Held' %><%= f.text_field :post_held %></p>
			<p class="formline"><%= f.label :duty_years, 'Years of Duty' %><%= f.text_field :duty_years %></p>
			<p class="formline"><%= f.label :state %><%= f.text_field :state %></p>
			<p class="formline"><%= f.label :nationality %><%= f.text_field :nationality %></p>
			<p class="formline"><%= f.label :town, 'Local Government Area' %><%= f.text_field :town %></p>
			<p class="formline"><%= f.label :family_address, 'Family Address' %><%= f.text_field :family_address %></p>
			<p class="formline"><%= f.label :permanent_address, 'Permanet Address' %><%= f.text_field :permanent_address %></p>
			<p class="formline"><%= f.label :residence, 'Residential Address' %><%= f.text_field :residence %></p>
			<p class="formline"><%= f.label :kin, 'Next of Kin' %><%= f.text_field :kin %></p>
			<p class="formline"><%= f.label :kin_phone, "Next of Kin's Phone" %><%= f.text_field :kin_phone %></p>
			<p class="formline"><%= f.label :kin_address, "Next of Kin's Address" %><%= f.text_field :kin_address %></p>
			<p class="formline"><%= f.label :annual_salary, 'Annual Salary' %><%= f.text_field :annual_salary %></p>
			<p class="formline"><button class="btn-std">Add staff</button></p>
		<% end %>
	</div>
</section>

app/views/staffs/show.html.erb
<% if @staff.avatar.eql? nil %>
<%= image_tag 'vader.jpg',alt: 'profile',class: 'staffImage' %>
<% else %>
<img src="<%= @staff.avatar %>" class="staffImage" alt="profile">
<% end %>
<section class="staffData">
	<div class="topbar">
		<% if current_user.role.eql? 'administrator' %>
		<div class="fl">
			<span><%= link_to 'Edit', edit_staff_path %></span>
			<span><%= link_to 'Delete', @staff, method: 'delete', 'data-confirm' => 'Are you sure?' %></span>
		</div>
		<% end %>
		<a href="javascript:print()">
			<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="25" height="25" viewBox="0 0 32 32">
			<g id="icomoon-ignore"></g>
			<path d="M8 2h16v4h-16zM30 8h-28c-1.1 0-2 0.9-2 2v10c0 1.1 0.9 2 2 2h6v8h16v-8h6c1.1 0 2-0.9 2-2v-10c0-1.1-0.9-2-2-2zM22 28h-12v-10h12v10zM30.45 11c0 0.801-0.649 1.45-1.45 1.45s-1.45-0.649-1.45-1.45 0.649-1.45 1.45-1.45c0.801 0 1.45 0.649 1.45 1.45z" fill="#333333"></path>
			</svg>
		</a>
	</div>
	<div class="entry">
		<em>staff since <%= @staff.staff_from %></em>
		<p><strong>Title:</strong><span><%= "#{@staff.title}".capitalize %></span></p>
		<p><strong>Surname:</strong><span><%= "#{@staff.surname}".capitalize %></span></p>
		<p><strong>Other names:</strong><span><%= @staff.othernames %></span></p>
		<p><strong>Mother's maiden name:</strong><span><%= @staff.maiden_name %></span></p>
		<p><strong>Gender:</strong><span><%= @staff.gender %></span></p>
		<p><strong>Date of birth:</strong><span><%= @staff.date_of_birth %></span></p>
		<p><strong>marital status:</strong><span><%= @staff.marital_status %></span></p>
		<p><strong>Spouse name:</strong><span><%= @staff.spouse %></span></p>
		<p><strong>Name of first child:</strong><span><%= @staff.first_child %></span></p>
		<p><strong>Phone:</strong><span><%= @staff.phone %></span></p>
		<p><strong>Email:</strong><span><%= @staff.email %></span></p>
		<p><strong>Department:</strong><span><%= "#{@staff.department}".capitalize %></span></p>
		<p><strong>Designation:</strong><span><%= "#{@staff.designation}".capitalize %></span></p>
		<p><strong>Previous employer:</strong><span><%= @staff.prev_employer %></span></p>
		<p><strong>Post held:</strong><span><%= @staff.post_held %></span></p>
		<p><strong>Years of duty:</strong><span><%= @staff.duty_years %></span></p>
		<p><strong>State of origin:</strong><span><%= @staff.state %></span></p>
		<p><strong>Nationality:</strong><span><%= @staff.nationality %></span></p>
		<p><strong>City:</strong><span><%= @staff.city %></span></p>
		<p><strong>Local government area:</strong><span><%= @staff.town %></span></p>
		<p><strong>Family house address:</strong><span><%= @staff.family_address %></span></p>
		<p><strong>Permanent Home address:</strong><span><%= @staff.permanent_address %></span></p>
		<p><strong>Residential address:</strong><span><%= @staff.residence %></span></p>
		<p><strong>Next of kin:</strong><span><%= @staff.kin %></span></p>
		<p><strong>Phone of Next of Kin:</strong><span><%= @staff.kin_phone %></span></p>
		<p><strong>Address of Next of kin:</strong><span><%= @staff.kin_address %></span></p>
	</div>
</section>