config/routes.rb
Rails.application.routes.draw do
  delete 'activities/clear' => 'activities#clear', as: :activity_clear
  get 'activities' => 'activities#index', as: :activities
  get 'departments/*param' => 'departments#categories', as: :department_cat
  get 'login' => 'sessions#new', as: :log_in
  get 'logout' => 'sessions#destroy', as: :log_out
  resources :sessions, :users, :staffs, :departments, :loans, :sabbaticals, :attendances, :preferences, :reliefs, :announcements
  get 'dashboard/user' => 'dashboard#user', as: :dashboard_user
  get 'dashboard/company' => 'dashboard#company', as: :dashboard_company
  get 'dashboard/preferences' => 'dashboard#preferences', as: :dashboard_setting
  get 'dashboard/records' => 'dashboard#records', as: :dashboard_records
  get 'dashboard' => 'dashboard#index', as: :dashboard
  get 'login'   => 'sessions#new'
  get 'forgot'  => 'sessions#forgot'

  root 'sessions#new'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :staff
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/loan.rb
class Loan < ActiveRecord::Base
	belongs_to :staff
end

app/models/preference.rb
class Preference < ActiveRecord::Base
end

app/models/relief.rb
class Relief < ActiveRecord::Base
	belongs_to :staff
end

app/models/sabbatical.rb
class Sabbatical < ActiveRecord::Base
	belongs_to :staff
	validates :staff_id, presence: true
end

app/models/staff.rb
class Staff < ActiveRecord::Base
	has_many :loans, :dependent => :destroy
	has_many :sabbaticals, :dependent => :destroy
	has_many :attendances, :dependent => :destroy
	has_many :reliefs, :dependent => :destroy
	has_attached_file :avatar, bucket: 'vitabiotics-assets', styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}, default_url: ':attachment/missing.png', storage: :s3, url: ":s3_domain_url", path: "/images/:id/:style.:extension",
	s3_host_name: 's3.amazonaws.com', s3_credentials: "#{Rails.root}/config/aws.yml"
	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email
	has_attached_file :avatar, bucket: 'vitabiotics-assets', styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}, default_url: ':attachment/missing.png', storage: :s3, url: ":s3_domain_url", path: "/images/:id/:style.:extension",
	s3_host_name: 's3.amazonaws.com', s3_credentials: "#{Rails.root}/config/aws.yml"
	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_login
  before_filter :init

  def index
    @departments.each do |department|
      childfetch = Department.where(parent: "#{department.name}").select('name')
      instance_variable_set("@#{department.name}Children".gsub(' ','_'), childfetch.map { |child| "#{child.name}" }.join(',') )
    end
    @activities = Activity.where(user_id: current_user.id).order("updated_at DESC").take(5)
    all_records = Attendance.pluck(:date, :presence).map { |attendance, presence| [attendance.strftime('%B'), presence] }
    @attendances = all_records.group_by(&:first).map do |k, v|
      trues, falses = v.partition(&:last); [k, "#{(Float(trues.size)/ (Float(falses.size) + Float(trues.size)) * 100).round}%"]
    end
    @announcement = Announcement.new
  end
  def records
    @loans = Loan.take(5)
    @sabbaticals = Sabbatical.take(5)
    @reliefs = Relief.take(5)
    @attendances = Attendance.take(5)
  end
  def preferences
    @preference = Preference.find(1)
    # Colors in RGB
    @colors = ['221, 17, 66','170, 85, 204','32, 144, 172','238, 102, 17','192, 195, 204']
  end
  def company
    @department = Department.new
    @allDepartments = Department.all.order('created_at ASC')
    @department_array = @departments.all.map { |dept| [dept.name, dept.name] }
  end
  def user
    @user = User.new
    @user_update = User.find(current_user.id)
  end

  private

  def require_login
    unless session[:user_id].present?
      redirect_to root_url
    end
  end
  def init
    @departments = Department.where(parent: '').order('created_at ASC')
    @preferences = Preference.find(1)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
	def instancevars(arg)
		instance_variable_get("@#{arg}Children".gsub(' ','_'))
	end
	def nameslug(arg)
		arg.downcase[0,5]
	end
	def color_label(arg)
		"theme_#{arg.gsub(', ','_')}"
	end
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/reliefs_helper.rb
module ReliefsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/company.html.erb
<section class="row-doubles">
	<div>
		<div class="title">Add Department</div>
		<div class="content pad10">
			<%= content_tag :p, flash.notice, class: 'notifier' %>
			<%= form_for @department do |f| %>
			<p>
				<%= f.label :name, 'Department Name' %>
				<%= f.text_field :name %>
			</p>
			<p>
				<%= f.label :parent %>
				<%= f.select :parent, options_for_select([['no parent', '']] + @department_array) %>
			</p>
			<%= f.submit 'Add Department', class: 'btn-std' %>
			<% end %>
		</div>
		<div class="topmag10">
			<div class="content blue color-white pad10 clearfix">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="40" height="40" viewBox="0 0 32 32" class="fl">
				<path d="M12 23c0-4.726 2.996-8.765 7.189-10.319 0.509-1.142 0.811-2.411 0.811-3.681 0-4.971 0-9-6-9s-6 4.029-6 9c0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h12.416c-0.271-0.954-0.416-1.96-0.416-3z" fill="#FFFFFF"></path>
				<path d="M23 14c-4.971 0-9 4.029-9 9s4.029 9 9 9c4.971 0 9-4.029 9-9s-4.029-9-9-9zM28 24h-4v4h-2v-4h-4v-2h4v-4h2v4h4v2z" fill="#FFFFFF"></path>
				</svg>
				<strong class="pad10 block fl"><%= link_to 'Add Staffs', new_staff_path %></strong>
			</div>
		</div>
		<div class="topmag10">
			<div class="content background-money-green color-white pad10 clearfix">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="40" height="40" viewBox="0 0 32 32" class="fl">
				<path d="M15 2c-8.284 0-15 6.716-15 15s6.716 15 15 15c8.284 0 15-6.716 15-15s-6.716-15-15-15zM15 29c-6.627 0-12-5.373-12-12s5.373-12 12-12c6.627 0 12 5.373 12 12s-5.373 12-12 12zM16 16v-4h4v-2h-4v-2h-2v2h-4v8h4v4h-4v2h4v2h2v-2h4l-0-8h-4zM14 16h-2v-4h2v4zM18 22h-2v-4h2v4z" fill="#FFFFFF"></path>
				</svg>
				<strong class="pad10 block fl"><%= link_to 'Add Loans', new_loan_path %></strong>
			</div>
		</div>
		<div class="topmag10">
			<div class="content background-deep-orange color-white pad10 clearfix">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32" class="fl">
				<path d="M32 10l-16-8-16 8 16 8 16-8zM16 4.655l10.689 5.345-10.689 5.345-10.689-5.345 10.689-5.345zM28.795 14.398l3.205 1.602-16 8-16-8 3.205-1.602 12.795 6.398zM28.795 20.398l3.205 1.602-16 8-16-8 3.205-1.602 12.795 6.398z" fill="#FFFFFF"></path>
				</svg>
				<strong class="pad10 block fl"><%= link_to 'Add Sabbatical', new_sabbatical_path %></strong>
			</div>
		</div>
		<div class="topmag10">
			<div class="content background-pure-orange color-white pad10 clearfix">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32" class="fl">
				<path d="M10 12h4v4h-4zM16 12h4v4h-4zM22 12h4v4h-4zM4 24h4v4h-4zM10 24h4v4h-4zM16 24h4v4h-4zM10 18h4v4h-4zM16 18h4v4h-4zM22 18h4v4h-4zM4 18h4v4h-4zM26 0v2h-4v-2h-14v2h-4v-2h-4v32h30v-32h-4zM28 30h-26v-22h26v22z" fill="#FFFFFF"></path>
				</svg>
				<strong class="pad10 block fl"><%= link_to 'Add Attendance', new_attendance_path %></strong>
			</div>
		</div>
		<div class="topmag10">
			<div class="content background-deep-purple color-white pad10 clearfix">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32" class="fl">
				<path d="M0 32c4-12 14.469-32 32-32-8.219 6.594-12 22-18 22s-6 0-6 0l-6 10h-2z" fill="#FFFFFF"></path>
				</svg>
				<strong class="pad10 block fl"><%= link_to 'Add Relief', new_relief_path %></strong>
			</div>
		</div>
	</div>
	<div>
		<div class="title">Departments</div>
		<div id="department-list">
			<main class="list">
				<% @allDepartments.all.map do |department| %>
				<div class="topmag10 deptname">
					<div class="content pad10 clearfix">
						<%= "#{department.name}" %>
						<div class="fr">
							<span>Edit</span>
							<span><%= link_to "Delete", department, method: 'delete', 'data-confirm' => "Are you sure?" %></span>
						</div>
						<aside>
							<%= form_for department, remote: true do |f| %>
							<%= f.label 'Department Name' %>
							<%= f.text_field :name, value: "#{department.name}" %>
							<%= f.label :Parent %>
							<%= f.select :parent, options_for_select([['no parent', '']] + @department_array, "#{department.parent}") %>
							<%= f.hidden_field :id, value: "#{department.id}" %>
							<%= f.submit :update, class: 'btn-edit' %>
							<% end %>
						</aside>
					</div>
				</div>
				<% end %>
			</main>
			<ul class="pagination"></ul>
		</div>
	</div>
</section>

app/views/dashboard/index.html.erb
<section class="head-image" data-stellar-background-ratio="0.5" style="background-image: url(<%= @preferences.header == nil ? image_path('abstract.jpg') : "/uploads/#{@preferences.header}" %>)">
	<div class="layer"><h2><%= "#{current_user.role}".capitalize %></h2></div>
</section>
<section class="row-two">
	<div>
		<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="32" viewBox="0 0 36 32" class="background-pure-orange">
		<path d="M24 24.082v-1.649c2.203-1.241 4-4.337 4-7.432 0-4.971 0-9-6-9s-6 4.029-6 9c0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h28c0-4.030-5.216-7.364-12-7.918z" fill="#FFFFFF"></path>
		<path d="M10.225 24.854c1.728-1.13 3.877-1.989 6.243-2.513-0.47-0.556-0.897-1.176-1.265-1.844-0.95-1.726-1.453-3.627-1.453-5.497 0-2.689 0-5.228 0.956-7.305 0.928-2.016 2.598-3.265 4.976-3.734-0.529-2.39-1.936-3.961-5.682-3.961-6 0-6 4.029-6 9 0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h8.719c0.454-0.403 0.956-0.787 1.506-1.146z" fill="#FFFFFF"></path>
		</svg>
		<h3><%= link_to 'All Staff', staffs_path %></h3><span>View all staffs</span>
	</div>
	<div>
		<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="40" height="40" viewBox="0 0 32 32" class="background-money-green">
		<path d="M15 2c-8.284 0-15 6.716-15 15s6.716 15 15 15c8.284 0 15-6.716 15-15s-6.716-15-15-15zM15 29c-6.627 0-12-5.373-12-12s5.373-12 12-12c6.627 0 12 5.373 12 12s-5.373 12-12 12zM16 16v-4h4v-2h-4v-2h-2v2h-4v8h4v4h-4v2h4v2h2v-2h4l-0-8h-4zM14 16h-2v-4h2v4zM18 22h-2v-4h2v4z" fill="#FFFFFF"></path>
		</svg>
		<h3><%= link_to 'Loans', loans_path %></h3><span>Granted loans</span>
	</div>
	<div>
		<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30" height="30" viewBox="0 0 32 32" class="background-cool-blue">
		<path d="M28 4h-3v1c0 1.103-0.897 2-2 2s-2-0.897-2-2v-1h-10v1c0 1.103-0.897 2-2 2s-2-0.897-2-2v-1h-3c-1.1 0-2 0.9-2 2v22c0 1.1 0.9 2 2 2h24c1.1 0 2-0.9 2-2v-22c0-1.1-0.9-2-2-2zM28 27.996c-0.001 0.001-0.002 0.003-0.004 0.004h-23.993c-0.001-0.001-0.003-0.002-0.004-0.004v-17.996h24v17.996zM9 6c0.552 0 1-0.448 1-1v-4c0-0.552-0.448-1-1-1s-1 0.448-1 1v4c0 0.552 0.448 1 1 1zM23 6c0.552 0 1-0.448 1-1v-4c0-0.552-0.448-1-1-1s-1 0.448-1 1v4c0 0.552 0.448 1 1 1zM18 12h-10v2h8v4h-8v2h8v4h-8v2h10zM22 26h2v-14h-4v2h2zM27.25 30.75h-22.5c-1.1 0-2-0.65-2-1.75v1c0 1.1 0.9 2 2 2h22.5c1.1 0 2-0.9 2-2v-1c0 1.1-0.9 1.75-2 1.75z" fill="#FFFFFF"></path>
		</svg>
		<h3><%= link_to 'Attendance', attendances_path %></a></h3><span>Monthly Attendance</span>
	</div>
	<div>
		<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32" class="background-deep-orange">
		<g id="icomoon-ignore"></g>
		<path d="M32 10l-16-8-16 8 16 8 16-8zM16 4.655l10.689 5.345-10.689 5.345-10.689-5.345 10.689-5.345zM28.795 14.398l3.205 1.602-16 8-16-8 3.205-1.602 12.795 6.398zM28.795 20.398l3.205 1.602-16 8-16-8 3.205-1.602 12.795 6.398z" fill="#FFFFFF"></path>
		</svg>
		<h3><%= link_to 'Sabbaticals', sabbaticals_path %></h3><span>Casual leave and more</span>
	</div>
</section>
<section class="row-doubles">
	<div>
		<div>
			<div class="title">Recent Activities</div>
			<div class="content pad10">
				<ul class="clean-list">
					<% @activities.map do |activity| %>
					<li><%= "#{activity.activity}".capitalize %> <em class="fr"><%= activity.created_at.strftime('%D') %></em></li>
					<% end %>
				</ul>
				<% if @activities.first == nil %>
				<p>No Recent Activities</p>
				<% else %>
				<%= link_to '<div class="read-more">Read more</div>'.html_safe, activities_path %>
				<% end %>
			</div>
		</div>
		<div class="topmag10 background-cool-blue pad20">
			<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="40" height="40" viewBox="0 0 32 32" class="background-cool-blue">
			<g id="icomoon-ignore"></g>
			<path d="M28 4h-3v1c0 1.103-0.897 2-2 2s-2-0.897-2-2v-1h-10v1c0 1.103-0.897 2-2 2s-2-0.897-2-2v-1h-3c-1.1 0-2 0.9-2 2v22c0 1.1 0.9 2 2 2h24c1.1 0 2-0.9 2-2v-22c0-1.1-0.9-2-2-2zM28 27.996c-0.001 0.001-0.002 0.003-0.004 0.004h-23.993c-0.001-0.001-0.003-0.002-0.004-0.004v-17.996h24v17.996zM9 6c0.552 0 1-0.448 1-1v-4c0-0.552-0.448-1-1-1s-1 0.448-1 1v4c0 0.552 0.448 1 1 1zM23 6c0.552 0 1-0.448 1-1v-4c0-0.552-0.448-1-1-1s-1 0.448-1 1v4c0 0.552 0.448 1 1 1zM18 12h-10v2h8v4h-8v2h8v4h-8v2h10zM22 26h2v-14h-4v2h2zM27.25 30.75h-22.5c-1.1 0-2-0.65-2-1.75v1c0 1.1 0.9 2 2 2h22.5c1.1 0 2-0.9 2-2v-1c0 1.1-0.9 1.75-2 1.75z" fill="#FFFFFF"></path>
			</svg><h2 class="color-white">Attendance Chart</h2>
			<ul class="clean-list color-white">
				<% @attendances.each do |attendance| %>
				<li><%= attendance[0] %><strong class="fr"><%= attendance[1] %></strong></li>
				<% end %>
			</ul>
			<% if @attendances.present? != false %>
			<a href=""><div class="read-more color-white">Read more</div></a>
			<% else %>
			<p class="color-white">No attendance records</p>
			<% end %>
		</div>
	</div>
	<div>
		<div class="title">Departments</div>
		<div class="content pad10">
			<ul class="accord-style">
				<% @departments.each do |department| %>
				<li <%= instancevars(department.name).present? ? "data-accord=#{nameslug(department.name)}":'' %>>
					<%= link_to "#{department.name}", department.name.downcase.gsub(' ','-') %>
				</li>
					<% if(instancevars(department.name).present?) %>
					<ul id="<%= nameslug(department.name) %>">
						<% instancevars(department.name).split(',').each do |child| %>
						<li>
						<%= link_to "#{child}", department_cat_path(department.name.downcase.gsub(' ','-') +'/'+ child.downcase.gsub(' ','-')) %>
						</li>
						<% end %>
					</ul>
					<% end %>
				<% end %>
			</ul>
		</div>
		<!-- Announcements -->
		<div class="topmag10 background-deep-purple pad20 color-white">
			<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="40" height="40" viewBox="0 0 32 32">
			<path d="M12 16c0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.209-1.791 4-4 4s-4-1.791-4-4zM20.761 7.204c3.12 1.692 5.239 4.997 5.239 8.796s-2.119 7.104-5.239 8.796c1.377-2.191 2.239-5.321 2.239-8.796s-0.862-6.605-2.239-8.796zM9 16c0 3.475 0.862 6.605 2.239 8.796-3.12-1.692-5.239-4.997-5.239-8.796s2.119-7.104 5.239-8.796c-1.377 2.191-2.239 5.321-2.239 8.796zM3 16c0 5.372 1.7 10.193 4.395 13.491-4.447-2.842-7.395-7.822-7.395-13.491s2.948-10.649 7.395-13.491c-2.695 3.298-4.395 8.119-4.395 13.491zM24.605 2.509c4.447 2.842 7.395 7.822 7.395 13.491s-2.948 10.649-7.395 13.491c2.695-3.298 4.395-8.119 4.395-13.491s-1.7-10.193-4.395-13.491z" fill="#FFFFFF"></path>
			</svg><h2>Announcements</h2>
			<p>Broadcast an announcement</p>
			<%= form_for @announcement, remote: true, class: 'fancy-form' do |f| %>
				<%= f.text_area :message, placeholder: 'A brief message to everyone...', id: 'status', maxlength: '50' %>
				<%= f.submit :Broadcast %>
				<span id="text_counter" class="fr"></span>
			<% end %>
		</div>

	</div>
</section>

app/views/dashboard/records.html.erb
<section class="row-doubles">
	<!-- Left Pane -->
	<div>
		<div class="title">Loans</div>
		<div class="content pad10">
			<ul class="clean-list">
				<% @loans.map do |loan| %>
				<li>
					<%= "#{Staff.find(loan.staff_id).surname} #{Staff.find(loan.staff_id).othernames}" %>
					<em class="fr"><%= loan.amount %></em>
				</li>
				<% end %>
			</ul>
			<% if @loans.first == nil %>
			<p>No Loan Records created</p>
			<% else %>
			<%= link_to '<div class="read-more">Read more</div>'.html_safe, loans_path %>
			<% end %>
		</div>

		<div class="title topmag10">Reliefs</div>
		<div class="content pad10">
			<ul class="clean-list">
				<% @reliefs.map do |relief| %>
				<li>
					<%= "#{Staff.find(relief.staff_id).surname} #{Staff.find(relief.staff_id).othernames}" %>
					<em class="fr"><%= relief.category.capitalize %></em>
				</li>
				<% end %>
			</ul>
			<% if @reliefs.first == nil %>
			<p>No Relief Records created</p>
			<% else %>
			<%= link_to '<div class="read-more">Read more</div>'.html_safe, reliefs_path %>
			<% end %>
		</div>
	</div>
	<!-- Right Pane -->
	<div>
		<div class="title">Sabbaticals</div>
		<div class="content pad10">
			<ul class="clean-list">
				<% @sabbaticals.map do |sabbatical| %>
				<li>
					<%= "#{Staff.find(sabbatical.staff_id).surname} #{Staff.find(sabbatical.staff_id).othernames}" %>
					<em class="fr"><%= "#{sabbatical.category.capitalize}&nbsp;Leave".html_safe %></em>
				</li>
				<% end %>
			</ul>
			<% if @sabbaticals.first == nil %>
			<p>No Sabbatical Records created</p>
			<% else %>
			<%= link_to '<div class="read-more">Read more</div>'.html_safe, sabbaticals_path %>
			<% end %>
		</div>

		<div class="title topmag10">Attendance</div>
		<div class="content pad10">
			<ul class="clean-list">
				<% @attendances.map do |attendance| %>
				<li>
					<%= "#{Staff.find(attendance.staff_id).surname} #{Staff.find(attendance.staff_id).othernames}" %>
					<em class="fr"><%= attendance.presence == true ? 'present' : 'absent' %></em>
				</li>
				<% end %>
			</ul>
			<% if @attendances.first == nil %>
			<p>No Attendance Records created</p>
			<% else %>
			<%= link_to '<div class="read-more">Read more</div>'.html_safe, attendances_path %>
			<% end %>
		</div>
	</div>
</section>

app/views/dashboard/user.html.erb
<section class="row-doubles">
	<div>
		<div class="title">Edit Account</div>
		<div class="content pad10">
			<%= content_tag :p, flash.alert, class: 'notifier' %>
			<%= form_for @user_update do |f| %>
			<p>
				<%= f.label :firstname %>
				<%= f.text_field :firstname, value: "#{current_user.name == nil ? '' : current_user.name.split(' ')[0]}" %>
			</p>
			<p>
				<%= f.label :lastname %>
				<%= f.text_field :lastname, value: "#{current_user.name == nil ? '' : current_user.name.split(' ')[1]}" %>
			</p>
			<p>
				<%= f.label :email %>
				<%= email_field :user, :email, value: "#{current_user.email}", class: 'delicate', 'data-current' => "#{current_user.email}" %>
			</p>
			<p>
				<%= f.label :avatar %><br>
				<%= f.file_field :avatar %>
			</p>
			<p>
				<%= f.label :password, 'New Password (Leave blank to keep old password)' %>
				<%= f.password_field :password, class: 'delicate' %>
			</p>
			<p class="former ghost"></p>
			<%= f.submit 'Update Account', class: 'btn-std' %>
			<% end %>
		</div>
	</div>
	<div>
		<% if current_user.role == 'administrator' %>
		<div class="title">Add New User</div>
		<div class="content pad10">
			<%= content_tag :p, flash.notice, class: 'notifier' %>
			<%= form_for @user do |f| %>
			<p>
				<%= f.label :email %>
				<%= email_field :user, :email %>
			</p>
			<p>
				<%= f.label :role %>
				<%= f.select :role, options_for_select([['Administrator','administrator'],['Manager','manager']]) %>
			</p>
			<p>
				<%= f.label :password %>
				<%= f.password_field :password %>
			</p>
			<%= f.submit 'Add User', class: 'btn-std' %>
			<% end %>
		</div>
		<% end %>
		<div class="<%= current_user.role == 'administrator' ? 'topmag10': '' %>">
			<div class="content background-deep-orange color-white pad10 clearfix">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="32" viewBox="0 0 36 32" class="fl">
				<path d="M24 24.082v-1.649c2.203-1.241 4-4.337 4-7.432 0-4.971 0-9-6-9s-6 4.029-6 9c0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h28c0-4.030-5.216-7.364-12-7.918z" fill="#FFFFFF"></path>
				<path d="M10.225 24.854c1.728-1.13 3.877-1.989 6.243-2.513-0.47-0.556-0.897-1.176-1.265-1.844-0.95-1.726-1.453-3.627-1.453-5.497 0-2.689 0-5.228 0.956-7.305 0.928-2.016 2.598-3.265 4.976-3.734-0.529-2.39-1.936-3.961-5.682-3.961-6 0-6 4.029-6 9 0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h8.719c0.454-0.403 0.956-0.787 1.506-1.146z" fill="#EEEEEE"></path>
				</svg>
				<strong class="pad10 block fl"><%= link_to 'View and manage all existing users', users_path %></strong>
			</div>
		</div>
	</div>
</section>