config/routes.rb
Rails.application.routes.draw do
  delete 'activities/clear' => 'activities#clear', as: :activity_clear
  get 'activities' => 'activities#index', as: :activities
  get 'departments/*param' => 'departments#categories', as: :department_cat
  get 'login' => 'sessions#new', as: :log_in
  get 'logout' => 'sessions#destroy', as: :log_out
  resources :sessions, :users, :staffs, :departments, :loans, :sabbaticals, :attendances, :preferences, :reliefs, :announcements
  get 'dashboard/user' => 'dashboard#user', as: :dashboard_user
  get 'dashboard/company' => 'dashboard#company', as: :dashboard_company
  get 'dashboard/preferences' => 'dashboard#preferences', as: :dashboard_setting
  get 'dashboard/records' => 'dashboard#records', as: :dashboard_records
  get 'dashboard' => 'dashboard#index', as: :dashboard
  get 'login'   => 'sessions#new'
  get 'forgot'  => 'sessions#forgot'

  root 'sessions#new'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :staff
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/loan.rb
class Loan < ActiveRecord::Base
	belongs_to :staff
end

app/models/preference.rb
class Preference < ActiveRecord::Base
end

app/models/relief.rb
class Relief < ActiveRecord::Base
	belongs_to :staff
end

app/models/sabbatical.rb
class Sabbatical < ActiveRecord::Base
	belongs_to :staff
	validates :staff_id, presence: true
end

app/models/staff.rb
class Staff < ActiveRecord::Base
	has_many :loans, :dependent => :destroy
	has_many :sabbaticals, :dependent => :destroy
	has_many :attendances, :dependent => :destroy
	has_many :reliefs, :dependent => :destroy
	has_attached_file :avatar, bucket: 'vitabiotics-assets', styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}, default_url: ':attachment/missing.png', storage: :s3, url: ":s3_domain_url", path: "/images/:id/:style.:extension",
	s3_host_name: 's3.amazonaws.com', s3_credentials: "#{Rails.root}/config/aws.yml"
	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email
	has_attached_file :avatar, bucket: 'vitabiotics-assets', styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}, default_url: ':attachment/missing.png', storage: :s3, url: ":s3_domain_url", path: "/images/:id/:style.:extension",
	s3_host_name: 's3.amazonaws.com', s3_credentials: "#{Rails.root}/config/aws.yml"
	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
	before_filter :init
	before_action :require_login
	def index
		@loans = Loan.all
	end
	def new
		@loan = Loan.new
	end

	def create
		@loan = Loan.new(loan_params)
		if @loan.save
			Activity.new({'user_id' => current_user.id, 'activity' => "Created a loan record" }).save
			redirect_to :back, notice: 'Loan record created'
		else
			render "new", notice: 'Failed to create loan record'
		end
	end

	def show
		@loan = Loan.find(params[:id])
		loanList = Loan.where(staff_id: @loan.staff_id, paid: false).pluck(:amount)
		loanSum = 0
		addition = loanList.each { |amount| loanSum += amount.gsub(/\D/,'').to_i }
		@outstanding = loanSum - @loan.amount.gsub(/\D/,'').to_i
	end

	def edit
		@loan = Loan.find(params[:id])
	end

	def update
		@loan = Loan.find(params[:id])
		updated = @loan.update_attributes(loan_params)
		if updated
			Activity.new({'user_id' => current_user.id, 'activity' => "Updated a loan record" }).save
			redirect_to :back, notice: 'Record updated'
		else
			render "edit"
		end
	end

	def destroy
		@loan = Loan.find(params[:id])
	    if @loan.destroy
	    	Activity.new({'user_id' => current_user.id, 'activity' => "Deleted a loan record" }).save
	    	redirect_to loans_path
	    end
	end

	private

	def loan_params
		params.require(:loan).permit!
	end
	def require_login
		unless session[:user_id].present?
	    	redirect_to root_url
		end
	end
	def init
		@preferences = Preference.find(1)
		@fetchStaff = Staff.all
		@staffs = @fetchStaff.all.map { |staff| ["#{staff.surname} #{staff.othernames}", staff.id] }
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
	def instancevars(arg)
		instance_variable_get("@#{arg}Children".gsub(' ','_'))
	end
	def nameslug(arg)
		arg.downcase[0,5]
	end
	def color_label(arg)
		"theme_#{arg.gsub(', ','_')}"
	end
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/reliefs_helper.rb
module ReliefsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/loans/edit.html.erb
<div class="middle-block" style="width:80%"><%= content_tag :p, notice, class: 'notifier' %></div>
<section class="staffData">
	<div class="topbar">
		Edit Loan record
	</div>
	<div class="entry">
		<%= form_for @loan do |f| %>
			<p class="formline">
				<%= f.label :staff_id, 'Staff' %>
				<%= f.select :staff_id, options_for_select([['Select staff', 0, disabled: 'true']] + @staffs, @loan.staff_id) %>
			</p>
			<p class="formline clearfix"><%= f.label :registration_no, 'Registration no' %><%= f.text_field :registration_no %></p>
			<p class="formline clearfix"><%= f.label :guarantor_name, 'Guarantor Name' %><%= f.text_field :guarantor_name %></p>
			<p class="formline clearfix"><%= f.label :guarantor_dept, 'Guarantor Department' %><%= f.text_field :guarantor_dept %></p>
			<p class="formline clearfix"><%= f.label :confirm_date, 'Date of Confirmation' %><%= f.date_field :confirm_date %></p>
			<p class="formline"><%= f.label :monthly_deduction %><%= f.text_field :monthly_deduction %></p>
			<p class="formline">
				<%= f.label :approval, 'Loan approval' %>
				<%= f.radio_button :approval, 'true' %> <span class="opt1">approved</span>
				<%= f.radio_button :approval, 'false' %> <span class="opt2">unapproved</span>
			</p>
			<p class="formline"><%= f.label :amount %><%= f.text_field :amount %></p>
			<p class="formline">
				<%= f.label :paid %>
				<%= f.radio_button :paid, 'true' %> <span class="opt1">yes</span>
				<%= f.radio_button :paid, 'false' %> <span class="opt2">no</span>
			</p>
			<p class="formline"><%= f.label :purpose, 'Purpose for Loan' %><%= f.text_area :purpose, size: '19x3' %></p>
			<p class="formline">&nbsp;</p>
			<p class="formline"><button class="btn-std">Update Loan Record</button></p>
		<% end %>
	</div>
</section>

app/views/loans/index.html.erb
<section class="row-doubles" id="department-list">
	<h1>All Loan Records</h1>
	<ul class="broken-list list">
		<% @loans.map do |loan| %>
		<li class="dotted deptname">
			<strong><%= "#{Staff.find(loan.staff_id).surname} #{Staff.find(loan.staff_id).othernames}" %></strong>
			<span><%= loan.amount %></span>
			<time><%= loan.confirm_date.strftime('%e %B, %Y') if loan.confirm_date %></time>
			<%= link_to '<button>View detailed</button>'.html_safe, loan_path(loan.id), class: 'link', style: 'top: 5px' %>
		</li>
		<% end %>
	</ul>
	<ul class="pagination"></ul>
</section>

app/views/loans/new.html.erb
<div class="middle-block" style="width:80%"><%= content_tag :p, notice, class: 'notifier' %></div>
<section class="staffData">
	<div class="topbar">
		Add a Loan record
	</div>
	<div class="entry">
		<%= form_for @loan do |f| %>
			<p class="formline">
				<%= f.label :staff_id, 'Staff' %>
				<%= f.select :staff_id, options_for_select(@staffs) %>
			</p>
			<p class="formline clearfix"><%= f.label :registration_no, 'Registration no' %><%= f.text_field :registration_no %></p>
			<p class="formline clearfix"><%= f.label :guarantor_name, 'Guarantor Name' %><%= f.text_field :guarantor_name %></p>
			<p class="formline clearfix"><%= f.label :guarantor_dept, 'Guarantor Department' %><%= f.text_field :guarantor_dept %></p>
			<p class="formline clearfix"><%= f.label :confirm_date, 'Date of Confirmation' %><%= f.date_field :confirm_date %></p>
			<p class="formline"><%= f.label :monthly_deduction %><%= f.text_field :monthly_deduction %></p>
			<p class="formline">
				<%= f.label :loan_approved, 'Loan approval' %>
				<%= f.radio_button :loan_approved, 'true' %> <span class="opt1">approved</span>
				<%= f.radio_button :loan_approved, 'false' %> <span class="opt2">unapproved</span>
			</p>
			<p class="formline"><%= f.label :amount %><%= f.text_field :amount %></p>
			<p class="formline"><%= f.label :loan_purpose, 'Purpose for Loan' %><%= f.text_area :loan_purpose, size: '19x3' %></p>
			<p class="formline">&nbsp;</p>
			<p class="formline"><button class="btn-std">Create Loan Record</button></p>
		<% end %>
	</div>
</section>

app/views/loans/show.html.erb
<section class="staffData">
	<div class="topbar">
		<% if current_user.role.eql? 'administrator' %>
		<div class="fl">
			<span><%= link_to 'Edit', edit_loan_path %></span>
			<span><%= link_to 'Delete', @loan, method: 'delete', 'data-confirm' => 'Are you sure?' %></span>
		</div>
		<% end %>
	</div>
	<div class="entry">
		<em>Loan Record for <%= "#{Staff.find(@loan.staff_id).surname} #{Staff.find(@loan.staff_id).othernames}" %></em>
		<p><strong>Registration number:</strong><span><%= @loan.registration_no %></span></p>
		<p><strong>Employment date:</strong><span><%= "#{Staff.find(@loan.staff_id).staff_from}" %></span></p>
		<p><strong>Annual Salary:</strong><span><%= "#{Staff.find(@loan.staff_id).annual_salary}" %></span></p>
		<p><strong>Department:</strong><span><%= "#{Staff.find(@loan.staff_id).department}" %></span></p>
		<p><strong>Guarantor:</strong><span><%= @loan.guarantor_name %></span></p>
		<p><strong>Guarantor's department:</strong><span><%= @loan.guarantor_dept %></span></p>
		<p><strong>Amount:</strong><span><%= @loan.amount %></span></p>
		<p><strong>Approval:</strong><span><%= @loan.approval == true ? 'Approved':'Not Approved' %></span></p>
		<p><strong>Monthly Deduction:</strong><span><%= @loan.monthly_deduction %></span></p>
		<p><strong>Previous Loan debts:</strong><span><%= @outstanding %></span></p>
		<p><strong>Payment status:</strong><span><%= @loan.paid == true ? 'Paid': 'Not paid' %></span></p>
		<p><strong>Purpose of Loan:</strong><span><%= @loan.purpose %></span><br><br><br></p>
	</div>
</section>