config/routes.rb
Rails.application.routes.draw do
  delete 'activities/clear' => 'activities#clear', as: :activity_clear
  get 'activities' => 'activities#index', as: :activities
  get 'departments/*param' => 'departments#categories', as: :department_cat
  get 'login' => 'sessions#new', as: :log_in
  get 'logout' => 'sessions#destroy', as: :log_out
  resources :sessions, :users, :staffs, :departments, :loans, :sabbaticals, :attendances, :preferences, :reliefs, :announcements
  get 'dashboard/user' => 'dashboard#user', as: :dashboard_user
  get 'dashboard/company' => 'dashboard#company', as: :dashboard_company
  get 'dashboard/preferences' => 'dashboard#preferences', as: :dashboard_setting
  get 'dashboard/records' => 'dashboard#records', as: :dashboard_records
  get 'dashboard' => 'dashboard#index', as: :dashboard
  get 'login'   => 'sessions#new'
  get 'forgot'  => 'sessions#forgot'

  root 'sessions#new'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :staff
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/loan.rb
class Loan < ActiveRecord::Base
	belongs_to :staff
end

app/models/preference.rb
class Preference < ActiveRecord::Base
end

app/models/relief.rb
class Relief < ActiveRecord::Base
	belongs_to :staff
end

app/models/sabbatical.rb
class Sabbatical < ActiveRecord::Base
	belongs_to :staff
	validates :staff_id, presence: true
end

app/models/staff.rb
class Staff < ActiveRecord::Base
	has_many :loans, :dependent => :destroy
	has_many :sabbaticals, :dependent => :destroy
	has_many :attendances, :dependent => :destroy
	has_many :reliefs, :dependent => :destroy
	has_attached_file :avatar, bucket: 'vitabiotics-assets', styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}, default_url: ':attachment/missing.png', storage: :s3, url: ":s3_domain_url", path: "/images/:id/:style.:extension",
	s3_host_name: 's3.amazonaws.com', s3_credentials: "#{Rails.root}/config/aws.yml"
	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email
	has_attached_file :avatar, bucket: 'vitabiotics-assets', styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}, default_url: ':attachment/missing.png', storage: :s3, url: ":s3_domain_url", path: "/images/:id/:style.:extension",
	s3_host_name: 's3.amazonaws.com', s3_credentials: "#{Rails.root}/config/aws.yml"
	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
	def instancevars(arg)
		instance_variable_get("@#{arg}Children".gsub(' ','_'))
	end
	def nameslug(arg)
		arg.downcase[0,5]
	end
	def color_label(arg)
		"theme_#{arg.gsub(', ','_')}"
	end
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/reliefs_helper.rb
module ReliefsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="ostrich-dev">
	<link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,300' rel='stylesheet' type='text/css'>
	<link rel="author" href="http://ostrich-dev.com">
	<link rel="shortcut icon" href="<%= "#{root_url}favicon.ico" %>">
	<title><%= @preferences.company %></title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<!-- Scripts -->
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
<!-- Sidebar -->
<section class="sidebar">
	<header title="<%= @preferences.company %>"><%= link_to @preferences.company.capitalize, root_url %></header>
	<%= image_tag current_user.avatar.url %>
	<h3 title="<%= current_user.name == nil ? '' : current_user.name.split(' ')[0] %>">
		<%= current_user.name == '' || current_user.name == ' ' || current_user.name == nil ? 'No' : current_user.name.split(' ')[0] %>
	</h3>
	<h4 title="<%= current_user.name == nil ? '' : current_user.name.split(' ')[1] %>">
		<%= current_user.name == '' || current_user.name == ' ' || current_user.name == nil ? 'Name' : current_user.name.split(' ')[1] %>
	</h4>
	<ul>
		<li class="<%= request.path == '/dashboard' ? 'active':'' %>">
			<%= link_to dashboard_path do %>
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 32 32">
				<g id="icomoon-ignore"></g>
				<path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM9.464 26.067c0.347-0.957 0.536-1.99 0.536-3.067 0-3.886-2.463-7.197-5.913-8.456 0.319-2.654 1.508-5.109 3.427-7.029 2.267-2.266 5.28-3.515 8.485-3.515s6.219 1.248 8.485 3.515c1.92 1.92 3.108 4.375 3.428 7.029-3.45 1.26-5.913 4.57-5.913 8.456 0 1.077 0.189 2.11 0.536 3.067-1.928 1.258-4.18 1.933-6.536 1.933s-4.608-0.675-6.536-1.933zM17.242 20.031c0.434 0.109 0.758 0.503 0.758 0.969v2c0 0.55-0.45 1-1 1h-2c-0.55 0-1-0.45-1-1v-2c0-0.466 0.324-0.86 0.758-0.969l0.742-14.031h1l0.742 14.031z"></path>
				</svg>
				Dashboard
			<% end %>
		</li>
		<li class="<%= request.path == '/dashboard/records' ? 'active':'' %>">
			<%= link_to dashboard_records_path do %>
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="20" viewBox="0 0 36 32">
				<path d="M7 4h-6c-0.55 0-1 0.45-1 1v22c0 0.55 0.45 1 1 1h6c0.55 0 1-0.45 1-1v-22c0-0.55-0.45-1-1-1zM6 10h-4v-2h4v2z"></path>
				<path d="M17 4h-6c-0.55 0-1 0.45-1 1v22c0 0.55 0.45 1 1 1h6c0.55 0 1-0.45 1-1v-22c0-0.55-0.45-1-1-1zM16 10h-4v-2h4v2z"></path>
				<path d="M23.909 5.546l-5.358 2.7c-0.491 0.247-0.691 0.852-0.443 1.343l8.999 17.861c0.247 0.491 0.852 0.691 1.343 0.443l5.358-2.7c0.491-0.247 0.691-0.852 0.443-1.343l-8.999-17.861c-0.247-0.491-0.852-0.691-1.343-0.443z"></path>
				<path d="M29 27c0 0.552-0.448 1-1 1s-1-0.448-1-1c0-0.552 0.448-1 1-1s1 0.448 1 1z"></path>
				</svg>
				Records
			<% end %>
		</li>
		<% if current_user.role == 'administrator' %>
		<li class="<%= request.path == '/dashboard/company' ? 'active':'' %>">
			<%= link_to dashboard_company_path do %>
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 32 32">
				<g id="icomoon-ignore"></g>
				<path d="M0 32h16v-32h-16v32zM10 4h4v4h-4v-4zM10 12h4v4h-4v-4zM10 20h4v4h-4v-4zM2 4h4v4h-4v-4zM2 12h4v4h-4v-4zM2 20h4v4h-4v-4zM18 10h14v2h-14zM18 32h4v-8h6v8h4v-18h-14z"></path>
				</svg>
				Company Settings
			<% end %>
		</li>
		<% end %>
		<li class="<%= request.path == '/dashboard/user' ? 'active':'' %>">
			<%= link_to dashboard_user_path do %>
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 32 32">
				<g id="icomoon-ignore"></g>
				<path d="M26.5 32h-21c-0.828 0-1.5-0.672-1.5-1.5 0-2.152 0.908-4.756 2.43-6.967 1.272-1.847 2.834-3.238 4.521-4.050-0.744-0.676-1.384-1.501-1.891-2.441-0.813-1.508-1.242-3.252-1.242-5.041 0-2.488 0.819-4.838 2.306-6.618 1.552-1.858 3.639-2.881 5.876-2.881s4.324 1.023 5.876 2.882c1.487 1.78 2.306 4.131 2.306 6.618 0 1.79-0.43 3.533-1.242 5.041-0.507 0.941-1.147 1.765-1.891 2.441 1.687 0.812 3.25 2.203 4.521 4.050 1.521 2.21 2.43 4.815 2.43 6.967 0 0.828-0.672 1.5-1.5 1.5zM7.19 29h17.62c-0.288-1.229-0.891-2.575-1.711-3.766-1.295-1.882-2.912-3.113-4.551-3.466-0.691-0.149-1.184-0.76-1.184-1.466v-1.072c0-0.539 0.29-1.037 0.758-1.304 1.859-1.057 3.060-3.383 3.060-5.926 0-3.584-2.325-6.5-5.182-6.5s-5.182 2.916-5.182 6.5c0 2.543 1.201 4.869 3.060 5.926 0.469 0.267 0.758 0.764 0.758 1.304v1.072c0 0.707-0.493 1.317-1.184 1.466-1.639 0.353-3.256 1.584-4.551 3.466-0.82 1.191-1.423 2.537-1.711 3.766z"></path>
				</svg>
				User Settings
			<% end %>
		</li>
		<% if current_user.role == 'administrator' %>
		<li class="<%= request.path == '/dashboard/preferences' ? 'active':'' %>">
			<%= link_to dashboard_setting_path do %>
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 32 32">
				<g id="icomoon-ignore"></g>
				<path d="M11.366 22.564l1.291-1.807-1.414-1.414-1.807 1.291c-0.335-0.187-0.694-0.337-1.071-0.444l-0.365-2.19h-2l-0.365 2.19c-0.377 0.107-0.736 0.256-1.071 0.444l-1.807-1.291-1.414 1.414 1.291 1.807c-0.187 0.335-0.337 0.694-0.443 1.071l-2.19 0.365v2l2.19 0.365c0.107 0.377 0.256 0.736 0.444 1.071l-1.291 1.807 1.414 1.414 1.807-1.291c0.335 0.187 0.694 0.337 1.071 0.444l0.365 2.19h2l0.365-2.19c0.377-0.107 0.736-0.256 1.071-0.444l1.807 1.291 1.414-1.414-1.291-1.807c0.187-0.335 0.337-0.694 0.444-1.071l2.19-0.365v-2l-2.19-0.365c-0.107-0.377-0.256-0.736-0.444-1.071zM7 27c-1.105 0-2-0.895-2-2s0.895-2 2-2 2 0.895 2 2-0.895 2-2 2zM32 12v-2l-2.106-0.383c-0.039-0.251-0.088-0.499-0.148-0.743l1.799-1.159-0.765-1.848-2.092 0.452c-0.132-0.216-0.273-0.426-0.422-0.629l1.219-1.761-1.414-1.414-1.761 1.219c-0.203-0.149-0.413-0.29-0.629-0.422l0.452-2.092-1.848-0.765-1.159 1.799c-0.244-0.059-0.492-0.109-0.743-0.148l-0.383-2.106h-2l-0.383 2.106c-0.251 0.039-0.499 0.088-0.743 0.148l-1.159-1.799-1.848 0.765 0.452 2.092c-0.216 0.132-0.426 0.273-0.629 0.422l-1.761-1.219-1.414 1.414 1.219 1.761c-0.149 0.203-0.29 0.413-0.422 0.629l-2.092-0.452-0.765 1.848 1.799 1.159c-0.059 0.244-0.109 0.492-0.148 0.743l-2.106 0.383v2l2.106 0.383c0.039 0.251 0.088 0.499 0.148 0.743l-1.799 1.159 0.765 1.848 2.092-0.452c0.132 0.216 0.273 0.426 0.422 0.629l-1.219 1.761 1.414 1.414 1.761-1.219c0.203 0.149 0.413 0.29 0.629 0.422l-0.452 2.092 1.848 0.765 1.159-1.799c0.244 0.059 0.492 0.109 0.743 0.148l0.383 2.106h2l0.383-2.106c0.251-0.039 0.499-0.088 0.743-0.148l1.159 1.799 1.848-0.765-0.452-2.092c0.216-0.132 0.426-0.273 0.629-0.422l1.761 1.219 1.414-1.414-1.219-1.761c0.149-0.203 0.29-0.413 0.422-0.629l2.092 0.452 0.765-1.848-1.799-1.159c0.059-0.244 0.109-0.492 0.148-0.743l2.106-0.383zM21 15.35c-2.402 0-4.35-1.948-4.35-4.35s1.948-4.35 4.35-4.35 4.35 1.948 4.35 4.35c0 2.402-1.948 4.35-4.35 4.35z"></path>
				</svg>
				Preferences
			<% end %>
		</li>
		<% end %>
	</ul>
	<div class="loader">
		<span id="el"></span>
	</div>
</section>
<!-- End of Sidebar -->
<section class="board">
	<header>
		<form action=""><input type="text" name="search" placeholder="search..."></form>
		<ul>
			<li title="Settings">
				<%= link_to current_user.role == 'administrator' ? dashboard_setting_path : dashboard_user_path do %>
					<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 32 32">
					<g id="icomoon-ignore"></g>
					<path d="M14 4v-0.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-6v4h6v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h18v-4h-18zM8 8v-4h4v4h-4zM26 13.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-18v4h18v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h6v-4h-6v-0.5zM20 18v-4h4v4h-4zM14 23.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-6v4h6v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h18v-4h-18v-0.5zM8 28v-4h4v4h-4z"></path>
					</svg>
				<% end %>
			</li>
			<li title="Notifications">
				<% if Announcement.where(receiver: current_user.id, read: false).first != nil %>
				<small></small>
				<% end %>
				<%= link_to announcements_path do %>
					<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 32 32">
					<g id="icomoon-ignore"></g>
					<path d="M32.047 25c0-9-8-7-8-14 0-0.58-0.056-1.076-0.158-1.498-0.526-3.532-2.88-6.366-5.93-7.23 0.027-0.123 0.041-0.251 0.041-0.382 0-1.040-0.9-1.891-2-1.891s-2 0.851-2 1.891c0 0.131 0.014 0.258 0.041 0.382-3.421 0.969-5.966 4.416-6.039 8.545-0.001 0.060-0.002 0.121-0.002 0.183 0 7-8 5-8 14 0 2.382 5.331 4.375 12.468 4.878 0.673 1.263 2.002 2.122 3.532 2.122s2.86-0.86 3.532-2.122c7.137-0.503 12.468-2.495 12.468-4.878 0-0.007-0.001-0.014-0.001-0.021l0.048 0.021zM25.82 26.691c-1.695 0.452-3.692 0.777-5.837 0.958-0.178-2.044-1.893-3.648-3.984-3.648s-3.805 1.604-3.984 3.648c-2.144-0.18-4.142-0.506-5.837-0.958-2.332-0.622-3.447-1.318-3.855-1.691 0.408-0.372 1.523-1.068 3.855-1.691 2.712-0.724 6.199-1.122 9.82-1.122s7.109 0.398 9.82 1.122c2.332 0.622 3.447 1.318 3.855 1.691-0.408 0.372-1.523 1.068-3.855 1.691z"></path>
					</svg>
				<% end %>
			</li>
			<li title="Sign Out">
				<%= link_to log_out_path do %>
					<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 32 32">
					<g id="icomoon-ignore"></g>
					<path d="M31.317 9.82l-3.16-3.159c-0.775-0.775-2.043-2.043-2.818-2.818l-3.16-3.159c-0.775-0.775-2.155-0.911-3.067-0.304l-8.639 5.759c-0.912 0.608-1.257 1.907-0.767 2.887l2.203 4.405c0.067 0.135 0.145 0.278 0.231 0.427l-11.142 11.142-1 7h6v-2h4v-4h4v-4h4v-2.225c0.2 0.119 0.392 0.226 0.569 0.314l4.405 2.203c0.98 0.49 2.279 0.145 2.887-0.767l5.759-8.639c0.608-0.912 0.471-2.292-0.304-3.066zM4.707 26.707l-1.414-1.414 9.737-9.737 1.414 1.414-9.737 9.737zM28.657 13.243l-1.414 1.414c-0.389 0.389-1.025 0.389-1.414 0l-8.485-8.485c-0.389-0.389-0.389-1.025 0-1.414l1.414-1.414c0.389-0.389 1.025-0.389 1.414 0l8.485 8.485c0.389 0.389 0.389 1.025 0 1.414z"></path>
					</svg>
				<% end %>
			</li>
		</ul>
	</header>
<%= yield %>
</section>
</body>
</html>

app/views/layouts/global.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="ostrich-dev">
	<link href='//fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<link rel="shortcut icon" href="<%= "#{root_url}favicon.ico" %>">
	<%= yield :title %>
</head>
<body>
	<%= yield %>
	<!-- Scripts -->
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>